### ISSUE TITLE
Why use 3.7-dev when testing .travis.yml?

### ISSUE THREAD

**Issue by endormi** [python/peps#1120] opened 2019-07-10 11:41 UTC
Why use 3.7-dev while it's not needed anymore and also why not test with other versions?

**Comment by brettcannon** [comment] 2019-07-10 22:37
This doesn't seem to be tied to any specific PEP, so I'm closing this issue. If this is a general question then it's best asked elsewhere.

**Comment by gvanrossum** [comment] 2019-07-10 22:41
Presumably it was about `travis.yml` in the peps repo, which does have the line `3.7-dev` under the `python` heading.

**Comment by brettcannon** [comment] 2019-07-11 18:57
Ah, thanks for the clarification @gvanrossum  and sorry about the misunderstanding, @endormi !

So I can answer both questions. We use `3.7-dev` because we want to use this repo as a very cheap "canary in the coal mine" test for the stable release of Python, and so we want to test against the in-development version and not just the official releases of Python.

And we don't test on other versions because we don't want to worry about code compatibility with other versions of Python with this repo.

So I'm still going to close this, but hopefully this answered your questions, @endormi .

**Comment by brandtbucher** [comment] 2020-02-11 05:16
For what it's worth, #1303 is experiencing a [failure](https://travis-ci.org/python/peps/jobs/648747071?utm_medium=notification&utm_source=github_status) on `3.7-dev` due to what *looks* like a bad virtualenv activation:

```
$ pip --version
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
$ pip install docutils
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

The `3.7` build is fine, though. I'm wondering if we could mark `3.7-dev` as `allow_failures`?

**Comment by brandtbucher** [comment] 2020-02-11 05:20
It looks like this is [affecting](https://travis-ci.org/python/peps/jobs/648604138?utm_medium=notification&utm_source=github_status) `master`, too.

**Comment by endormi** [comment] 2020-02-12 19:07
What do you think @brettcannon ?

**Comment by pradyunsg** [comment] 2020-02-12 21:34
This, looks to me, like it is related to the virtualenv 20.0 release.

There are some quirks of virtualenv 20.0 + Travis CI situation which might be causing these issues. It'd probably be useful to let virtualenv know (or comment on the existing issue there) that the issue is affecting this repository.

It's 3am on my end and I'm on mobile, so pardon my lack of searching/crosslinking issues.

**Comment by hugovk** [comment] 2020-05-04 15:05
`master` has been green for some time now.

https://travis-ci.org/github/python/peps/builds

The early virtualenv 20 releases had some Travis teething problems, but are sorted now.

OK to close this?

**Closed** 2020-05-04 19:19 UTC
