### ISSUE TITLE
Screen is cropped on a mobile phone

### ISSUE THREAD

**Issue by sfermigier** [python/peps#2441] opened 2022-03-17 16:34 UTC
Screenshot from my Android Phone:

![photo_2022-03-17 17 31 39](https://user-images.githubusercontent.com/271079/158848449-f0a25888-f94f-46ec-9b75-9d24edb9f499.jpeg)

Also screenshots using Firefox developers tools in various resolutions:
![Screen Shot 2022-03-17 at 17 27 37](https://user-images.githubusercontent.com/271079/158848649-6c4d7602-f36b-4fa6-8597-bf07ab8ddb31.png)
![Screen Shot 2022-03-17 at 17 27 37](https://user-images.githubusercontent.com/271079/158848683-fae5b38a-3161-41ea-b165-188861d79124.png)

Note that even if the lines weren't cropped like they are, a few more pixels of margin would be better.

**Comment by hugovk** [comment] 2022-03-17 16:38
Thanks for the report! This is a duplicate of https://github.com/python/peps/issues/2437 and the good news is there's a fix in progress: https://github.com/python/peps/pull/2439.

**Closed by hugovk** 2022-03-17 16:38 UTC
