### ISSUE TITLE
Could you add IDLE style syntax highlighting to the python code in PEP 8 and provide it in pdf format?

### ISSUE THREAD

**Issue by starcrescent** [python/peps#159] opened 2016-12-16 08:33 UTC

**Comment by brettcannon** [comment] 2016-12-16 17:33
While this is technically two requests in one issue and would normally need to be broken up into individual issues, both could/would be resolved if #2 ever occurs. So I'm going to close this as implicitly a duplicate of #2 .

**Closed by brettcannon** 2016-12-16 17:33 UTC
Labels: enhancement
