### ISSUE TITLE
admonitions don't get rendered correctly

### ISSUE THREAD

**Issue by warsaw** [python/peps#109] opened 2016-09-26 15:46 UTC
As per http://docutils.sourceforge.net/docs/ref/rst/directives.html#note I would expect admonitions such as `.. note:` to be rendered in a text box, but that doesn't seem to be the case.  See https://www.python.org/dev/peps/pep-0339/ and https://www.python.org/dev/peps/pep-0042/ (as soon as that gets regenerated).

**Comment by berkerpeksag** [comment] 2016-09-26 15:49
This is a duplicate of https://github.com/python/pythondotorg/issues/428.

**Closed** 2016-09-27 17:07 UTC
